[package]
name = "work_hours"
version = "0.1.0"
authors = ["Kris Ralph <kris.ralph45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"

[lib]
name = "work_hours"
